### ISSUE TITLE
Define responses the app will give to uses based on trust

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/Trust-Open-Access#9]
Depending on what lists the journal turns up on, we'll need to give some indication to the user on the level of trust. This indication can be a notification, content in the app, links to show etc. 

E.g If they're on a list e.g Seal of approval/OASPA we can be sure they're not predatory, so should give a response saying that. If they're not an Open Access journal, we should give another response.

**Comment by dommitchell** [comment]
Our thoughts on this:

(Corresponds to #8 )

*GREEN*
In short:	'Go ahead. This is a trusted open access journal'
Includes:	All journals in DOAJ with the The Tick [https://doaj.org/publishers#thetick]
		All truly open-access journals from OASPA members. (NO hybrid journals.)
Links to:	Information about what 'Green OK' means. A link in the app goes to the journal's page in DOAJ, for example: https://doaj.org/toc/1179-5565.
		The journal *may* charge APCs. Information about OAB and DOAJ.
		What to do for OASPA journals that are not in DOAJ? Where do they link?

*YELLOW*
In short:	'Proceed with caution.'
Includes:	All journals in DOAJ with no Tick. (Approx 9000.)
Links to: 	Information on why a journal is yellow: 
			- The journal is currently under evaluation at the DOAJ
			- The journal is in DOAJ but doesn't have the Tick
		A link that goes to the journal page in DOAJ, for example: https://doaj.org/toc/2044-6055.
		Where we are unable to provide a link to a page in DOAJ, it links to a page where we provide information as to what an author should check for before submitting to the journal: 'Is it a questionable journal? Check before you submit!' (Possibly link to campaign on this page.) Information about OAB and DOAJ.

*RED*
In short:	'Warning. This journal is not open access.'
Includes:	Journals that are not open access. [Data source to be confirmed.]
		All subscription-based journals which includes hybrid journals (subscription journals with an open access option). [Data source to be confirmed.]
Links to: 	An information page about what Red means, about the benefits of submitting to an open journal, about OAB and about DOAJ.

*NOTHING* (could be a '?')
In short:	'We have no data on this journal.'
Includes:	This would probably mainly be journals considered to be questionable.
		Could include young open access journals that haven't applied to be in DOAJ yet.
		Will include any other journal that we do not know about.
Links to: 	An information page about what nothing (or ?) means, what are questionable journals, how to check for questionable journals, about OAB and DOAJ.

**Comment by mtb-za** [comment]
I like that idea. Is nice and simple.

Are OASPA journals necessarily trusted?

**Comment by dommitchell** [comment]
> Are OASPA journals necessarily trusted?

Yep, but we should check directly with OASPA. I will ask Lars for a contact unless someone at OAB has one already?

**Comment by davidecarroll** [comment]
What about people who are colourblind?

**Comment by ajrbyers** [comment]
@davidecarroll could also display:

tick for good
cross for bad
exclamation mark for warning

**Comment by ISfourOA** [comment]
Regarding OASPA: the (fully) Open Access journals from OASPA members are trusted, but remember most OASPA members as well have subscription/hybrid journals - which in our context are red/bad.

I have contacts when needed

**Comment by ISfourOA** [comment]
re colourblind and display

David is right - I think I agree with the suggestions + the question mark category

**Comment by ISfourOA** [comment]
BTW: ISfourOA is Lars commenting

**Comment by dommitchell** [comment]
> tick for good
> cross for bad
> exclamation mark for warning

Agreed!

**Comment by JosephMcArthur** [comment]
Why are we listing hybrid journals and subscription journals as red/!? In my mind this is about ensuring people are able to verify (easily) that Open Access journals have high standards (good peer review, not predatory etc). So, hybrid journals would be treated similarly to Open Access journals in that scheme, while subscription journals might not need a response at all, or a simply a "not open access" type response. I'd use a "!" for when a journal is Open Access but isn't in the DOAJ (or has been removed).

**Comment by ISfourOA** [comment]
Joe,

A hybrid journal is a subscription journal with an open access option,
where the author/her grant/institution pays for her article to be open/free.

Hybrid articles are generally twice as expensive as articles published in
those genuine OA-journals that do charge APCs.

It is my agenda to promote genuine OA-journals, and not hybrid/subscription
journals. Hybrid (open access options) are generally considered yet another
cash-cow for those publishers who already gets the buck!

Lars

On Thu, Aug 27, 2015 at 9:57 PM, Joseph McArthur <notifications@github.com>
wrote:

> Why are we listing hybrid journals and subscription journals as red/!? In
> my mind this is about ensuring people are able to verify (easily) that Open
> Access journals have high standards (good peer review, not predatory etc).
> So, hybrid journals would be treated similarly to Open Access journals in
> that scheme, while subscription journals might not need a response at all,
> or a simply a "not open access" type response. I'd use a "!" for when a
> journal is Open Access but isn't in the DOAJ (or has been removed).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/Trust-Open-Access/issues/9#issuecomment-135536290>
> .
>



-- 

Lars Bjørnshauge
Managing Director
DOAJ

**Comment by JosephMcArthur** [comment]
While hybrid journals may cost more, and I'm certainly not their biggest
fan, in terms of quality/peer review etc the price their charging isn't
relevant.

While I have no issue pointing out to users when something is a hybrid
journal we should reserve the !/red response for cases where a journal may
be predatory or there are concerns about quality etc. If we show a warning
too often (e.g on all hybrids) we risk it becoming meaningless to a user
and so no longer useful.

In any responses content we can indicate if a journal is a hybrid if the
data is available.

**Comment by ajrbyers** [comment]
I dunno, I think you could class some hybrid journals as predatory. They take APCs and don't pass that saving on to those who pay subscription charges, that sounds like double dipping and dodgy practice to me...

**Comment by markmacgillivray** [comment]
There is a difference between those partaking in dodgy practices and those
that are not then - but if that distinction can be made at all, then
clearly just being hybrid is not an indicator of untrustworthiness.

**Comment by georginaetaylor** [comment]
I don't think we should be flagging ANY journals as 'red/bad' (subscription or otherwise). Reasons: 1) as others have said, being a hybrid/subscription journal doesn't make you untrustworthy 2) there's a potential for mislabelling that could hurt a decent OA journal 3) even for actual predatory OA journals, I'd be concerned about opening ourselves up to legal action in marking them as such and 4) I don't think there's a need for it, if our aim is to generate trust in good quality OA journals then we can showcase this alone - without providing a list of bad ones.

I would think pure subscription journals wouldn't be a 'red/bad/warning' as just marked as subscription and greyed out in some way without much, if any, further data. In my mind we're setting Open as the default and helping people find a good one from that starting point.

**Comment by dommitchell** [comment]
> I don't think we should be flagging ANY journals as 'red/bad' (subscription or otherwise).

Actually, the red flag is defined as 'Warning. This journal is not open access.' See above.

**Comment by dommitchell** [comment]
> @davidecarroll could also display:
> 
> tick for good
> cross for bad
> exclamation mark for warning

and question mark for 'No data'?

**Comment by JosephMcArthur** [comment]
Tried to take the above and turn it into something we could all agree with. Been sensitive to try and handle hybrids and journals with pretty clear issues carefully while maintaining simplicity. Colours and symbols can be used together I think. 

GREEN/tick
In short: 'Go ahead. This is a trusted open access journal'
Includes: All journals in DOAJ with the The Tick [https://doaj.org/publishers#thetick]
All open-access journals from OASPA members.
Links to: Information about what 'Green OK' means. A link in the app goes to the journal's page in DOAJ, for example: https://doaj.org/toc/1179-5565.

YELLOW/?
In short: 'Proceed with caution.'
Includes: All journals in DOAJ with no Tick. (Approx 9000.)
Links to: Information on why a journal is yellow: 
- The journal is currently under evaluation at the DOAJ
- The journal is in DOAJ but doesn't have the Tick
A link that goes to the journal page in DOAJ, for example: https://doaj.org/toc/2044-6055.
Where we are unable to provide a link to a page in DOAJ, it links to a page where we provide information as to what an author should check for before submitting to the journal: 'Is it a questionable journal? Check before you submit!' (Possibly link to campaign on this page.) Information about OAB and DOAJ.

RED/!
In short: Warning, check this journal.
This is meant to not be a definate, "you can't trust this", but more a big nudge to check it out before going forwards.
Includes: Journals who've been removed from the DOAJ for a clear reason (highlighted in Dom's recent comment)
Links to: ???

Yellow/$
In short: This is a subscription journal. 
Includes: Subscription journals. For hybrids, we could show this in combination with "the tick" or "?" or "!" and mention that hybrids have had comments about malpractice due to double charging libraries. 
Links to: An information page about the benefits of submitting to an open journal, about OAB and about DOAJ in tangent with other responses shown.

NOTHING/no symbol
In short: Not a journal
Includes: Every page on the internet which isn't a journal :)
Links to (if clicked): 
- A page to tell us this URL is actually a journal  
- An information page about what nothing (or ?) means.

**Comment by ISfourOA** [comment]
Thanks Joe,

I will come back tomorrow regarding this

Lars

On Wed, Sep 9, 2015 at 7:53 PM, Joseph McArthur <notifications@github.com>
wrote:

> Tried to take the above and turn it into something we could all agree
> with. Been sensitive to try and handle hybrids and journals with pretty
> clear issues carefully while maintaining simplicity. Colours and symbols
> can be used together I think.
>
> GREEN/tick
> In short: 'Go ahead. This is a trusted open access journal'
> Includes: All journals in DOAJ with the The Tick [
> https://doaj.org/publishers#thetick]
> All open-access journals from OASPA members.
> Links to: Information about what 'Green OK' means. A link in the app goes
> to the journal's page in DOAJ, for example: https://doaj.org/toc/1179-5565
> .
>
> YELLOW/?
> In short: 'Proceed with caution.'
> Includes: All journals in DOAJ with no Tick. (Approx 9000.)
> Links to: Information on why a journal is yellow:
>
>    - The journal is currently under evaluation at the DOAJ
>    - The journal is in DOAJ but doesn't have the Tick A link that goes to
>    the journal page in DOAJ, for example: https://doaj.org/toc/2044-6055.
>    Where we are unable to provide a link to a page in DOAJ, it links to a page
>    where we provide information as to what an author should check for before
>    submitting to the journal: 'Is it a questionable journal? Check before you
>    submit!' (Possibly link to campaign on this page.) Information about OAB
>    and DOAJ.
>
> RED/!
> In short: Warning, check this journal.
> This is meant to not be a definate, "you can't trust this", but more a big
> nudge to check it out before going forwards.
> Includes: Journals who've been removed from the DOAJ for a clear reason
> (highlighted in Dom's recent comment)
> Links to: ???
>
> Yellow/$
> In short: This is a subscription journal.
> Includes: Subscription journals. For hybrids, we could show this in
> combination with "the tick" or "?" or "!" and mention that hybrids have had
> comments about malpractice due to double charging libraries.
> Links to: An information page about the benefits of submitting to an open
> journal, about OAB and about DOAJ in tangent with other responses shown.
>
> NOTHING/no symbol
> In short: Not a journal
> Includes: Every page on the internet which isn't a journal :)
> Links to (if clicked):
>
>    - A page to tell us this URL is actually a journal
>    - An information page about what nothing (or ?) means.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/Trust-Open-Access/issues/9#issuecomment-138989598>
> .
>



-- 

Lars Bjørnshauge
Managing Director
DOAJ

**Comment by JosephMcArthur** [comment]
Having to close this issue now. @vesko-ski needs time to implement this before release. After that though, with feedback from others and further thought we can of course readdress it though!

**Comment by dommitchell** [comment]
@JosephMcArthur is the OASPA member journals list being used in the dataset at this moment? @vesko-ski maybe you know?
